use serde_json::Value;

use crate::behavior::{ToolBehavior, ToolMeta};
use crate::tier::Tier;

/// Compile-time description of one tool. Built from the
/// [`ToolBehavior`] impl + the [`ToolMeta`] constants the
/// `#[derive(Tool)]` macro emits.
///
/// The shape lines up one-for-one with the `tool-manifest` record in
/// `tool.wit` (PLUGIN-WASM.md) -- the wasm flavour serialises this
/// to the WIT type at `describe()` time, and the builtin flavour
/// hands it to the host's `ToolRegistry` adapter. The matching wire
/// format is what lets the same plugin source build into either
/// flavour without per-flavour manifest code.
#[derive(Debug, Clone)]
pub struct Manifest {
    pub id: &'static str,
    pub tier: Tier,
    pub description: &'static str,
    /// JSON Schema for the args object, generated by `schemars` from
    /// `<T as ToolBehavior>::Args`. The runner validates against it
    /// before `call` fires; MCP advertises it to LLM clients.
    pub input_schema: Value,
    /// JSON Schema for the return value. Plugins that produce
    /// attachments declare `{ "$ref": "codeless://attachment" }` in
    /// `Output` (via `#[schemars(schema_with = "...")]` on the field)
    /// so the Assistant agent loop renders the download card without
    /// per-plugin UI -- PS7 contract, preserved end-to-end through
    /// schemars's JSON-schema output.
    pub output_schema: Value,
}

impl Manifest {
    /// Build a `Manifest` for a concrete `ToolBehavior` impl. Runs
    /// `schemars` once per call, so cache the result behind a
    /// `OnceLock` if the host calls it on a hot path.
    pub fn for_behavior<T: ToolBehavior>() -> Self {
        let input_schema = serde_json::to_value(schemars::schema_for!(T::Args))
            .expect("schemars: T::Args schema serialises as JSON");
        let output_schema = serde_json::to_value(schemars::schema_for!(T::Output))
            .expect("schemars: T::Output schema serialises as JSON");
        Self {
            id: <T as ToolMeta>::ID,
            tier: <T as ToolMeta>::TIER,
            description: <T as ToolMeta>::DESCRIPTION,
            input_schema,
            output_schema,
        }
    }
}
