//! Emits the combined TypeScript wire contract that the UI compiles
//! against. The output is the concatenation of the two specta snapshots
//! (`codeless-types` core domain types and `codeless-rpc` method
//! args/results plus the subscribe filter) — both crates render their
//! own snapshot to avoid a `types -> rpc` dev-dependency cycle, and
//! this binary stitches them together at the seam where the UI consumes
//! a single module.
//!
//! Usage:
//!   cargo run -p codeless-rpc --example wire_ts -- <output-path>
//!
//! The output path defaults to
//! `ui/codeless-ui/src/lib/rpc/generated/wire.ts` resolved against the
//! inner-codeless repo root, which is what the UI build expects.
//!
//! This lives as an example (rather than a bin) because the
//! `specta-typescript` dependency only needs to exist at codegen time;
//! `[[example]]` targets resolve dev-dependencies, so `codeless-rpc`'s
//! normal build (and the mobile-reach graph it participates in) stays
//! free of the codegen-only crate.

use std::path::{Path, PathBuf};

use codeless_rpc::methods::{
    AddRepoArgs, AgentChatArgs, AgentChatResult, AppendAssistantMessageArgs,
    AppendAssistantMessageResult, ApproveReviewArgs, ApproveScopePatchArgs,
    CancelAssistantActionArgs, CancelAssistantActionResult, CancelChatTaskArgs, ChatAttachmentRef,
    ChatContext, ClaudeStatus, CommentReviewArgs, ConfirmAssistantActionArgs,
    ConfirmAssistantActionResult, CreateAssistantThreadArgs, DeleteAssistantThreadArgs,
    EditScopePatchArgs, FsCwdResult, FsReadDirArgs, FsReadDirResult, FsReadFileArgs,
    FsReadFileResult, FsStatArgs, FsStatResult, FsWriteFileArgs, GetJobArgs, JobDiffArgs,
    JobDiffFile, JobDiffResult, ListAssistantMessagesArgs, ListAssistantMessagesResult,
    ListAssistantThreadsArgs, ListAssistantThreadsResult, ListJobsArgs, ListJobsResult,
    ListReposResult, ListReviewsArgs, ListReviewsResult, RejectScopePatchArgs, RemoveRepoArgs,
    ResetJobArgs, RevertScopePatchArgs, RevertScopePatchResult, RunnerInfo, ScopePatchActionResult,
    ScopePatchResolution, ServerFeatureFlags, ServerInfo, StartJobArgs, StopActiveArgs,
    StopActiveResult, StopJobArgs, StopReviewArgs, SubmitJobArgs, UploadAssistantAttachmentArgs,
    UploadAssistantAttachmentResult, UploadChatAttachmentArgs, UploadChatAttachmentResult,
    UserPromptSnippet,
};
use codeless_rpc::subscribe::EventFilter;
use codeless_types::{
    AssistantAction, AssistantActionCard, AssistantActionStatus, AssistantAttachment,
    AssistantAttachmentId, AssistantMessage, AssistantMessageId, AssistantMessageRole,
    AssistantThread, AssistantThreadId, CostCents, Event, EventCursor, EventEnvelope, FsEntry,
    FsEntryKind, GitAuth, Handover, Job, JobId, JobStatus, PreCheckOutcome, Repo, RepoId, Review,
    ReviewId, ReviewStatus, ReviewVerdict, ScopePatch, ScopePatchId, ScopePatchKind,
    ScopePatchTarget, Stage, StageId, StageStatus, StopReason, Task, TaskId, TaskStatus,
    UnixMillis,
};
use specta::TypeCollection;
use specta_typescript::{BigIntExportBehavior, Typescript};

const HEADER: &str =
    "// This file is generated by `cargo run -p codeless-rpc --example wire_ts`.\n\
// Do not edit by hand. The Rust source of truth lives in\n\
// codeless-types (core domain) and codeless-rpc (method args, subscribe filter).\n\
// Regenerate after changing any of those, and commit the result.\n\n";

fn collect() -> TypeCollection {
    let mut types = TypeCollection::default();
    types
        .register_mut::<RepoId>()
        .register_mut::<JobId>()
        .register_mut::<StageId>()
        .register_mut::<TaskId>()
        .register_mut::<ReviewId>()
        .register_mut::<UnixMillis>()
        .register_mut::<CostCents>()
        .register_mut::<EventCursor>()
        .register_mut::<GitAuth>()
        .register_mut::<Repo>()
        .register_mut::<Job>()
        .register_mut::<JobStatus>()
        .register_mut::<StopReason>()
        .register_mut::<Stage>()
        .register_mut::<StageStatus>()
        .register_mut::<Task>()
        .register_mut::<TaskStatus>()
        .register_mut::<Review>()
        .register_mut::<ReviewStatus>()
        .register_mut::<Handover>()
        .register_mut::<Event>()
        .register_mut::<EventEnvelope>()
        .register_mut::<FsEntry>()
        .register_mut::<FsEntryKind>()
        .register_mut::<AddRepoArgs>()
        .register_mut::<RemoveRepoArgs>()
        .register_mut::<ListReposResult>()
        .register_mut::<SubmitJobArgs>()
        .register_mut::<GetJobArgs>()
        .register_mut::<ListJobsArgs>()
        .register_mut::<ListJobsResult>()
        .register_mut::<StopJobArgs>()
        .register_mut::<StartJobArgs>()
        .register_mut::<ResetJobArgs>()
        .register_mut::<ListReviewsArgs>()
        .register_mut::<ListReviewsResult>()
        .register_mut::<ApproveReviewArgs>()
        .register_mut::<CommentReviewArgs>()
        .register_mut::<StopReviewArgs>()
        .register_mut::<EventFilter>()
        .register_mut::<FsReadDirArgs>()
        .register_mut::<FsReadDirResult>()
        .register_mut::<FsReadFileArgs>()
        .register_mut::<FsReadFileResult>()
        .register_mut::<FsWriteFileArgs>()
        .register_mut::<FsStatArgs>()
        .register_mut::<FsStatResult>()
        .register_mut::<FsCwdResult>()
        .register_mut::<RunnerInfo>()
        .register_mut::<ClaudeStatus>()
        .register_mut::<ServerInfo>()
        .register_mut::<ServerFeatureFlags>()
        .register_mut::<JobDiffArgs>()
        .register_mut::<JobDiffFile>()
        .register_mut::<JobDiffResult>()
        .register_mut::<AgentChatArgs>()
        .register_mut::<AgentChatResult>()
        .register_mut::<ChatContext>()
        .register_mut::<ChatAttachmentRef>()
        .register_mut::<UserPromptSnippet>()
        .register_mut::<UploadChatAttachmentArgs>()
        .register_mut::<UploadChatAttachmentResult>()
        .register_mut::<CancelChatTaskArgs>()
        .register_mut::<StopActiveArgs>()
        .register_mut::<StopActiveResult>()
        .register_mut::<AssistantThreadId>()
        .register_mut::<AssistantMessageId>()
        .register_mut::<AssistantAttachmentId>()
        .register_mut::<AssistantThread>()
        .register_mut::<AssistantMessage>()
        .register_mut::<AssistantMessageRole>()
        .register_mut::<AssistantAttachment>()
        .register_mut::<ListAssistantThreadsArgs>()
        .register_mut::<ListAssistantThreadsResult>()
        .register_mut::<CreateAssistantThreadArgs>()
        .register_mut::<DeleteAssistantThreadArgs>()
        .register_mut::<UploadAssistantAttachmentArgs>()
        .register_mut::<UploadAssistantAttachmentResult>()
        .register_mut::<ListAssistantMessagesArgs>()
        .register_mut::<ListAssistantMessagesResult>()
        .register_mut::<AppendAssistantMessageArgs>()
        .register_mut::<AppendAssistantMessageResult>()
        .register_mut::<AssistantAction>()
        .register_mut::<AssistantActionStatus>()
        .register_mut::<AssistantActionCard>()
        .register_mut::<ConfirmAssistantActionArgs>()
        .register_mut::<ConfirmAssistantActionResult>()
        .register_mut::<CancelAssistantActionArgs>()
        .register_mut::<CancelAssistantActionResult>()
        .register_mut::<ScopePatchId>()
        .register_mut::<ScopePatchKind>()
        .register_mut::<ScopePatchTarget>()
        .register_mut::<ScopePatch>()
        .register_mut::<PreCheckOutcome>()
        .register_mut::<ReviewVerdict>()
        .register_mut::<ApproveScopePatchArgs>()
        .register_mut::<RejectScopePatchArgs>()
        .register_mut::<EditScopePatchArgs>()
        .register_mut::<ScopePatchResolution>()
        .register_mut::<ScopePatchActionResult>()
        .register_mut::<RevertScopePatchArgs>()
        .register_mut::<RevertScopePatchResult>();
    types
}

fn default_output_path() -> PathBuf {
    // CARGO_MANIFEST_DIR points at crates/codeless-rpc; the repo root
    // is two levels up. Keeping the path computed (not hardcoded as a
    // relative string) means `cargo run` from any directory still
    // writes to the correct file.
    let repo_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crate manifest must be nested under the repo root");
    repo_root.join("ui/codeless-ui/src/lib/rpc/generated/wire.ts")
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let output = args
        .get(1)
        .map(PathBuf::from)
        .unwrap_or_else(default_output_path);

    let types = collect();
    let ts = Typescript::default().bigint(BigIntExportBehavior::Number);
    let body = ts.export(&types).expect("export typescript");

    // Strip the per-call specta header so the file begins with the
    // codegen banner above, then re-emit the (deterministic) body. The
    // snapshot tests still validate that specta produced the expected
    // text; this file is the seam where two crates' snapshots become
    // one UI import.
    let body = body
        .strip_prefix(
            "// This file has been generated by Specta. Do not edit this file manually.\n",
        )
        .unwrap_or(&body);

    if let Some(parent) = output.parent() {
        std::fs::create_dir_all(parent).expect("create output dir");
    }
    let mut out = String::with_capacity(HEADER.len() + body.len());
    out.push_str(HEADER);
    out.push_str(body);

    std::fs::write(&output, &out).expect("write wire.ts");
    eprintln!("wrote {} bytes to {}", out.len(), output.display());
}
