// Generated by `wit-bindgen` 0.57.1. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod codeless {
    pub mod tool {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod tool {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        /// Tool risk classification used by the agent loop's confirmation
        /// policy. Mirrors `codeless_plugin_sdk::Tier`.
        #[repr(u8)]
        #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
        pub enum Tier {
          Read,
          Write,
          Destructive,
        }
        impl ::core::fmt::Debug for Tier {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              Tier::Read => {
                f.debug_tuple("Tier::Read").finish()
              }
              Tier::Write => {
                f.debug_tuple("Tier::Write").finish()
              }
              Tier::Destructive => {
                f.debug_tuple("Tier::Destructive").finish()
              }
            }
          }
        }

        impl Tier{
          #[doc(hidden)]
          pub unsafe fn _lift(val: u8) -> Tier{
            if !cfg!(debug_assertions) {
              return unsafe { ::core::mem::transmute(val) };
            }

            match val {
              0 => Tier::Read,
              1 => Tier::Write,
              2 => Tier::Destructive,

              _ => panic!("invalid enum discriminant"),
            }
          }
        }

        /// Identity + JSON Schemas for every tool the plugin contributes.
        /// `input-schema` / `output-schema` are JSON values serialised to
        /// strings -- the runner already validates JSON against schemas,
        /// so the wire format matches the validator. Binary attachments
        /// cross by attachment-id (PLUGIN-SUBSTRATE.md item 7), never
        /// inlined as bytes here.
        #[derive(Clone)]
        pub struct ToolManifest {
          pub id: _rt::String,
          pub description: _rt::String,
          pub input_schema: _rt::String,
          pub output_schema: _rt::String,
          pub tier: Tier,
        }
        impl ::core::fmt::Debug for ToolManifest {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("ToolManifest").field("id", &self.id).field("description", &self.description).field("input-schema", &self.input_schema).field("output-schema", &self.output_schema).field("tier", &self.tier).finish()
          }
        }
        #[derive(Clone)]
        pub struct ToolCall {
          pub tool_id: _rt::String,
          /// JSON value (already validated against `input-schema`),
          /// serialised to a string for the same reason as the schemas.
          pub args_json: _rt::String,
          /// Thread the call is scoped to. Used for attachment lookups
          /// and audit logging.
          pub thread_id: _rt::String,
        }
        impl ::core::fmt::Debug for ToolCall {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("ToolCall").field("tool-id", &self.tool_id).field("args-json", &self.args_json).field("thread-id", &self.thread_id).finish()
          }
        }
        #[derive(Clone)]
        pub struct ToolError {
          /// Stable machine-readable code (e.g. "limit-exceeded",
          /// "invalid-args"). The host maps a small set to its own
          /// structured-`Failed` reason vocabulary; unknown codes
          /// pass through as "plugin-error".
          pub code: _rt::String,
          pub message: _rt::String,
          /// Whether the agent loop should retry on this error. False
          /// for limit-exceeded, schema-mismatch, and any error the
          /// host classifies as fatal.
          pub retryable: bool,
        }
        impl ::core::fmt::Debug for ToolError {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("ToolError").field("code", &self.code).field("message", &self.message).field("retryable", &self.retryable).finish()
          }
        }
        #[derive(Clone)]
        pub enum ToolResult {
          /// JSON value (validated against `output-schema`), serialised.
          Ok(_rt::String),
          Err(ToolError),
        }
        impl ::core::fmt::Debug for ToolResult {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              ToolResult::Ok(e) => {
                f.debug_tuple("ToolResult::Ok").field(e).finish()
              }
              ToolResult::Err(e) => {
                f.debug_tuple("ToolResult::Err").field(e).finish()
              }
            }
          }
        }
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_describe_cabi<T_: Guest>() -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result0 = {
          T_::describe()
        };
        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
        let vec7 = result0;
        let len7 = vec7.len();
        let layout7 = _rt::alloc::Layout::from_size_align(vec7.len() * (9*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
        let (result7, _cleanup7) = wit_bindgen::rt::Cleanup::new(layout7);if let Some(cleanup) = _cleanup7 { cleanup.forget(); }
        for (i, e) in vec7.into_iter().enumerate() {
          let base = result7.add(i * (9*::core::mem::size_of::<*const u8>()));
          {
            let ToolManifest{ id:id2, description:description2, input_schema:input_schema2, output_schema:output_schema2, tier:tier2, } = e;
            let vec3 = (id2.into_bytes()).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
            let vec4 = (description2.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
            let vec5 = (input_schema2.into_bytes()).into_boxed_slice();
            let ptr5 = vec5.as_ptr().cast::<u8>();
            let len5 = vec5.len();
            ::core::mem::forget(vec5);
            *base.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
            *base.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5.cast_mut();
            let vec6 = (output_schema2.into_bytes()).into_boxed_slice();
            let ptr6 = vec6.as_ptr().cast::<u8>();
            let len6 = vec6.len();
            ::core::mem::forget(vec6);
            *base.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
            *base.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6.cast_mut();
            *base.add(8*::core::mem::size_of::<*const u8>()).cast::<u8>() = (tier2.clone() as i32) as u8;
          }
        }
        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
        *ptr1.add(0).cast::<*mut u8>() = result7;
        ptr1
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_describe<T_: Guest>(arg0: *mut u8,) { unsafe {
        let l0 = *arg0.add(0).cast::<*mut u8>();
        let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base10 = l0;
        let len10 = l1;
        for i in 0..len10 {
          let base = base10.add(i * (9*::core::mem::size_of::<*const u8>()));
          {
            let l2 = *base.add(0).cast::<*mut u8>();
            let l3 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l2, l3, 1);
            let l4 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l5 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l4, l5, 1);
            let l6 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l7 = *base.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l6, l7, 1);
            let l8 = *base.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l9 = *base.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l8, l9, 1);
          }
        }
        _rt::cabi_dealloc(base10, len10 * (9*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_call_cabi<T_: Guest>(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result3 = {
        let len0 = arg1;
        let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
        let len1 = arg3;
        let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
        let len2 = arg5;
        let bytes2 = _rt::Vec::from_raw_parts(arg4.cast(), len2, len2);
        T_::call(ToolCall{
          tool_id: _rt::string_lift(bytes0),
          args_json: _rt::string_lift(bytes1),
          thread_id: _rt::string_lift(bytes2),
        })
      };
      let ptr4 = (&raw mut _RET_AREA.0).cast::<u8>();
      match result3 {
        ToolResult::Ok(e) => {
          *ptr4.add(0).cast::<u8>() = (0i32) as u8;
          let vec5 = (e.into_bytes()).into_boxed_slice();
          let ptr5 = vec5.as_ptr().cast::<u8>();
          let len5 = vec5.len();
          ::core::mem::forget(vec5);
          *ptr4.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
          *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5.cast_mut();
        },
        ToolResult::Err(e) => {
          *ptr4.add(0).cast::<u8>() = (1i32) as u8;
          let ToolError{ code:code6, message:message6, retryable:retryable6, } = e;
          let vec7 = (code6.into_bytes()).into_boxed_slice();
          let ptr7 = vec7.as_ptr().cast::<u8>();
          let len7 = vec7.len();
          ::core::mem::forget(vec7);
          *ptr4.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
          *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr7.cast_mut();
          let vec8 = (message6.into_bytes()).into_boxed_slice();
          let ptr8 = vec8.as_ptr().cast::<u8>();
          let len8 = vec8.len();
          ::core::mem::forget(vec8);
          *ptr4.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
          *ptr4.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr8.cast_mut();
          *ptr4.add(5*::core::mem::size_of::<*const u8>()).cast::<u8>() = (match retryable6 { true => 1, false => 0 }) as u8;
        },
      }
      ptr4
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_call<T_: Guest>(arg0: *mut u8,) { unsafe {
      let l0 = i32::from(*arg0.add(0).cast::<u8>());
      match l0 {
        0 => {
          let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l1, l2, 1);
        },
        _ => {
          let l3 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l4 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l3, l4, 1);
          let l5 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l6 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l5, l6, 1);
        },
      }
    } }
    pub trait Guest {
      /// Identity + manifests for every tool the plugin contributes.
      #[allow(async_fn_in_trait)]
      fn describe() -> _rt::Vec::<ToolManifest>;
      /// Synchronous tool invocation. Long-running tools split into
      /// smaller calls; the streaming "action card -> confirmation ->
      /// result" event shape lives in the runtime, not in this ABI.
      #[allow(async_fn_in_trait)]
      fn call(req: ToolCall,) -> ToolResult;
    }
    #[doc(hidden)]

    macro_rules! __export_codeless_tool_tool_0_1_0_cabi{
      ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

        #[unsafe(export_name = "codeless:tool/tool@0.1.0#describe")]
        unsafe extern "C" fn export_describe() -> *mut u8 {
          unsafe { $($path_to_types)*::_export_describe_cabi::<$ty>() }
        }
        #[unsafe(export_name = "cabi_post_codeless:tool/tool@0.1.0#describe")]
        unsafe extern "C" fn _post_return_describe(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_describe::<$ty>(arg0) }
        }
        #[unsafe(export_name = "codeless:tool/tool@0.1.0#call")]
        unsafe extern "C" fn export_call(arg0: *mut u8,arg1: usize,arg2: *mut u8,arg3: usize,arg4: *mut u8,arg5: usize,) -> *mut u8 {
          unsafe { $($path_to_types)*::_export_call_cabi::<$ty>(arg0, arg1, arg2, arg3, arg4, arg5) }
        }
        #[unsafe(export_name = "cabi_post_codeless:tool/tool@0.1.0#call")]
        unsafe extern "C" fn _post_return_call(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_call::<$ty>(arg0) }
        }
      };);
    }
    #[doc(hidden)]
    pub(crate) use __export_codeless_tool_tool_0_1_0_cabi;

    #[cfg_attr(target_pointer_width="64", repr(align(8)))]
    #[cfg_attr(target_pointer_width="32", repr(align(4)))]
    struct _RetArea([::core::mem::MaybeUninit::<u8>; 6*::core::mem::size_of::<*const u8>()]);
    static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 6*::core::mem::size_of::<*const u8>()]);

  }

}
}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]
  pub use alloc_crate::string::String;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub use alloc_crate::alloc;
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub use alloc_crate::vec::Vec;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_plugin_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::codeless::tool::tool::__export_codeless_tool_tool_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::codeless::tool::tool);
  )
}
#[doc(inline)]
pub(crate) use __export_plugin_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.57.1:codeless:tool@0.1.0:plugin:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 471] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xda\x02\x01A\x02\x01\
A\x02\x01B\x0f\x01m\x03\x04read\x05write\x0bdestructive\x04\0\x04tier\x03\0\0\x01\
r\x05\x02ids\x0bdescriptions\x0cinput-schemas\x0doutput-schemas\x04tier\x01\x04\0\
\x0dtool-manifest\x03\0\x02\x01r\x03\x07tool-ids\x09args-jsons\x09thread-ids\x04\
\0\x09tool-call\x03\0\x04\x01r\x03\x04codes\x07messages\x09retryable\x7f\x04\0\x0a\
tool-error\x03\0\x06\x01q\x02\x02ok\x01s\0\x03err\x01\x07\0\x04\0\x0btool-result\
\x03\0\x08\x01p\x03\x01@\0\0\x0a\x04\0\x08describe\x01\x0b\x01@\x01\x03req\x05\0\
\x09\x04\0\x04call\x01\x0c\x04\0\x18codeless:tool/tool@0.1.0\x05\0\x04\0\x1acode\
less:tool/plugin@0.1.0\x04\0\x0b\x0c\x01\0\x06plugin\x03\0\0\0G\x09producers\x01\
\x0cprocessed-by\x02\x0dwit-component\x070.247.0\x10wit-bindgen-rust\x060.57.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

